using UnityEngine;using UnityEngine.SceneManagement;using UnityEngine.UI;using TMPro;
public class CityController:MonoBehaviour{
 GameData d;Canvas c;TextMeshProUGUI stats,msg;Transform grid;
 string[] names={"Homes","Farm","School","Solar Plant","Hospital","Market","Factory","Park","Water Plant","Transport","Research Lab","Stadium"};
 int[] cost={500,350,700,900,850,650,1400,600,1200,1100,1800,2200};
 void Start(){if(FindObjectOfType<GameApp>()==null)new GameObject("GameApp").AddComponent<GameApp>();d=GameApp.I.Data;Build();}
 TextMeshProUGUI T(string s,Transform p,int z){var g=new GameObject("Text");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;var t=g.AddComponent<TextMeshProUGUI>();t.text=s;t.fontSize=z;t.alignment=TextAlignmentOptions.Center;t.color=Color.white;t.enableAutoSizing=true;t.fontSizeMin=12;t.fontSizeMax=z;return t;}
 Button B(string s,Transform p){var g=new GameObject("Button");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.sizeDelta=new Vector2(280,170);g.AddComponent<Image>().color=new Color(.08f,.26f,.34f,1);var b=g.AddComponent<Button>();T(s,g.transform,25);return b;}
 void Build(){c=new GameObject("Canvas").AddComponent<Canvas>();c.renderMode=RenderMode.ScreenSpaceOverlay;var sc=c.gameObject.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1080,1920);c.gameObject.AddComponent<GraphicRaycaster>();var bg=new GameObject("BG");bg.transform.SetParent(c.transform,false);var br=bg.AddComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;bg.AddComponent<Image>().color=new Color(.035f,.08f,.10f,1);
 var title=T("BHARAT RISE • CITY",bg.transform,45);title.rectTransform.anchorMin=new Vector2(.03f,.93f);title.rectTransform.anchorMax=new Vector2(.97f,.99f);stats=T("",bg.transform,25);stats.rectTransform.anchorMin=new Vector2(.03f,.81f);stats.rectTransform.anchorMax=new Vector2(.97f,.92f);
 var gg=new GameObject("Buildings");gg.transform.SetParent(bg.transform,false);grid=gg.transform;var gl=gg.AddComponent<GridLayoutGroup>();gl.cellSize=new Vector2(280,150);gl.spacing=new Vector2(20,18);gl.constraint=GridLayoutGroup.Constraint.FixedColumnCount;gl.constraintCount=3;var gr=gg.GetComponent<RectTransform>();gr.anchorMin=new Vector2(.04f,.25f);gr.anchorMax=new Vector2(.96f,.80f);gr.offsetMin=gr.offsetMax=Vector2.zero;
 for(int i=0;i<names.Length;i++){int k=i;var b=B(names[i]+"\n₹"+cost[i],grid);b.onClick.AddListener(()=>BuildOne(k));}
 msg=T("Choose a district to develop.",bg.transform,23);msg.rectTransform.anchorMin=new Vector2(.04f,.19f);msg.rectTransform.anchorMax=new Vector2(.96f,.24f);
 var next=B("NEXT YEAR  ▶",bg.transform);Pos(next,.08f,.08f,.52f,.16f);next.onClick.AddListener(NextYear);var menu=B("MENU",bg.transform);Pos(menu,.55f,.08f,.92f,.16f);menu.onClick.AddListener(()=>SceneManager.LoadScene("MainMenu"));Refresh();}
 void Pos(Button b,float a,float c1,float x,float y){var r=b.GetComponent<RectTransform>();r.anchorMin=new Vector2(a,c1);r.anchorMax=new Vector2(x,y);r.offsetMin=r.offsetMax=Vector2.zero;}
 void BuildOne(int i){if(d.buildings[i]){msg.text=names[i]+" is already completed.";return;}if(d.money<cost[i]){msg.text="Not enough money.";return;}d.money-=cost[i];d.buildings[i]=true;d.population+=i==0?45:(i==9?15:0);d.food+=i==1?80:(i==5?25:0);d.energy+=i==3?100:(i==6?30:0);d.happiness=Mathf.Clamp(d.happiness+new[]{5,8,12,10,15,8,4,12,10,7,16,14}[i],0,100);d.xp+=100;d.level=Mathf.Clamp(1+d.xp/500,1,10);msg.text=names[i]+" completed!";GameApp.I.Save();Refresh();}
 void NextYear(){d.year++;d.money+=d.population*5+d.food/12;d.food=Mathf.Max(0,d.food-d.population/3);d.energy=Mathf.Max(0,d.energy-d.population/4);d.happiness=Mathf.Clamp(d.happiness+(d.food>0?2:-9)+(d.energy>0?2:-9),0,100);if(d.food<=0||d.energy<=0)d.population=Mathf.Max(40,d.population-15);msg.text="Year "+d.year+" started.";GameApp.I.Save();Refresh();}
 void Refresh(){stats.text=$"YEAR {d.year}  •  LEVEL {d.level}\n₹{d.money:N0}   👥 {d.population}   🌾 {d.food}   ⚡ {d.energy}   ❤ {d.happiness}%   XP {d.xp}";for(int i=0;i<grid.childCount;i++){var t=grid.GetChild(i).GetComponentInChildren<TextMeshProUGUI>();t.text=d.buildings[i]?names[i]+"\n✓ BUILT":names[i]+"\n₹"+cost[i];}}
}