using UnityEngine;using UnityEngine.SceneManagement;using UnityEngine.UI;using TMPro;using System.Collections;
public class CityController:MonoBehaviour{
 GameData d;Canvas canvas;TextMeshProUGUI stats,mission,message;Transform grid;bool dialogOpen;
 readonly string[] names={"Homes","Farm","School","Solar Plant","Hospital","Market","Factory","Park","Water Plant","Transport","Research Lab","Stadium"};
 readonly int[] cost={500,350,700,900,850,650,1400,600,1200,1100,1800,2200};
 readonly int[] joy={5,8,12,10,15,8,4,12,10,7,16,14};
 void Start(){if(GameApp.I==null)new GameObject("GameApp").AddComponent<GameApp>();d=GameApp.I.Data;BuildUI();if(!d.tutorialSeen)ShowDialog("WELCOME TO BHARAT RISE","You are the governor. Build a self-sustaining city, complete six chapters, reach Level 10 and unlock Free Build.");}
 TextMeshProUGUI Text(string s,Transform p,int size){var g=new GameObject("Text");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;var t=g.AddComponent<TextMeshProUGUI>();t.text=s;t.fontSize=size;t.alignment=TextAlignmentOptions.Center;t.color=Color.white;t.enableAutoSizing=true;t.fontSizeMin=12;t.fontSizeMax=size;return t;}
 Button Btn(string s,Transform p){var g=new GameObject("Button");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.sizeDelta=new Vector2(300,130);var im=g.AddComponent<Image>();im.color=new Color(.06f,.25f,.32f,1);var b=g.AddComponent<Button>();Text(s,g.transform,22);b.onClick.AddListener(()=>Pulse(g));return b;}
 void Pulse(GameObject g){if(d.reducedMotion)return;StartCoroutine(PulseRoutine(g.transform));}
 IEnumerator PulseRoutine(Transform t){var a=t.localScale;var b=a*1.04f;float x=0;while(x<1){x+=Time.unscaledDeltaTime*8;t.localScale=Vector3.Lerp(a,b,x);yield return null;}t.localScale=a;}
 void BuildUI(){canvas=new GameObject("BharatRiseCanvas").AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var sc=canvas.gameObject.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1080,1920);canvas.gameObject.AddComponent<GraphicRaycaster>();var bg=new GameObject("Background");bg.transform.SetParent(canvas.transform,false);var br=bg.AddComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;bg.AddComponent<Image>().color=new Color(.025f,.07f,.09f,1);
 var title=Text("BHARAT RISE",bg.transform,48);title.rectTransform.anchorMin=new Vector2(.03f,.94f);title.rectTransform.anchorMax=new Vector2(.97f,.99f);
 stats=Text("",bg.transform,22);stats.rectTransform.anchorMin=new Vector2(.03f,.82f);stats.rectTransform.anchorMax=new Vector2(.97f,.94f);
 mission=Text("",bg.transform,18);mission.rectTransform.anchorMin=new Vector2(.04f,.74f);mission.rectTransform.anchorMax=new Vector2(.96f,.82f);
 var gg=new GameObject("BuildingGrid");gg.transform.SetParent(bg.transform,false);grid=gg.transform;var gl=gg.AddComponent<GridLayoutGroup>();gl.cellSize=new Vector2(290,125);gl.spacing=new Vector2(16,14);gl.constraint=GridLayoutGroup.Constraint.FixedColumnCount;gl.constraintCount=3;var gr=gg.GetComponent<RectTransform>();gr.anchorMin=new Vector2(.03f,.25f);gr.anchorMax=new Vector2(.97f,.73f);gr.offsetMin=gr.offsetMax=Vector2.zero;
 for(int i=0;i<12;i++){int k=i;var b=Btn("",grid);b.onClick.AddListener(()=>BuildOrUpgrade(k));}
 message=Text("Choose a district.",bg.transform,18);message.rectTransform.anchorMin=new Vector2(.04f,.18f);message.rectTransform.anchorMax=new Vector2(.96f,.24f);
 var next=Btn("NEXT YEAR",bg.transform);Place(next,.06f,.06f,.48f,.15f);next.onClick.AddListener(NextYear);var menu=Btn("PAUSE / MENU",bg.transform);Place(menu,.52f,.06f,.94f,.15f);menu.onClick.AddListener(Pause);
 Refresh();}
 void Place(Button b,float x1,float y1,float x2,float y2){var r=b.GetComponent<RectTransform>();r.anchorMin=new Vector2(x1,y1);r.anchorMax=new Vector2(x2,y2);r.offsetMin=r.offsetMax=Vector2.zero;}
 void BuildOrUpgrade(int i){var b=d.buildings[i];int price=cost[i]*(b.level+1);if(b.level>=3){message.text=names[i]+" is at MAX level.";return;}if(d.money<price){message.text="Need "+price+" money for Level "+(b.level+1)+".";return;}if(b.level==0){d.totalBuilt++;}d.money-=price;b.level++;d.population+=i==0?35:0;d.food+=i==1?65:0;d.energy+=i==3?80:0;d.happiness=Mathf.Clamp(d.happiness+joy[i],0,100);d.xp+=100*b.level;d.level=Mathf.Clamp(1+d.xp/500,1,10);message.text=names[i]+" upgraded to Level "+b.level+"!";Missions.Advance(d);GameApp.I.Save();Refresh();}
 void NextYear(){if(dialogOpen)return;d.year++;int foodGain=d.buildings[1].level*70+d.buildings[5].level*15;int energyGain=d.buildings[3].level*80+d.buildings[8].level*35;d.money+=d.population*5+d.food/12+d.buildings[5].level*80;d.food=Mathf.Max(0,d.food+foodGain-d.population/3);d.energy=Mathf.Max(0,d.energy+energyGain-d.population/4);d.happiness=Mathf.Clamp(d.happiness+(d.food>0?2:-9)+(d.energy>0?2:-9)+d.buildings[7].level,0,100);if(d.food==0||d.energy==0)d.population=Mathf.Max(40,d.population-15);string ev=CityEvents.Apply(d);Missions.Advance(d);GameApp.I.Save();message.text=ev;if(d.cityComplete)ShowDialog("CITY COMPLETE","Congratulations! You completed every chapter and unlocked Free Build.");Refresh();}
 void Pause(){ShowDialog("PAUSED","Your city is safely saved. Continue when ready, or return to the main menu.","CONTINUE");}
 void ShowDialog(string title,string body,string button="START"){dialogOpen=true;var panel=new GameObject("Dialog");panel.transform.SetParent(canvas.transform,false);var r=panel.AddComponent<RectTransform>();r.anchorMin=new Vector2(.08f,.28f);r.anchorMax=new Vector2(.92f,.72f);r.offsetMin=r.offsetMax=Vector2.zero;panel.AddComponent<Image>().color=new Color(.03f,.12f,.15f,.98f);var t=Text(title+"\n\n"+body,panel.transform,25);t.rectTransform.anchorMin=new Vector2(.08f,.25f);t.rectTransform.anchorMax=new Vector2(.92f,.88f);var b=Btn(button,panel.transform);Place(b,.25f,.06f,.75f,.22f);b.onClick.AddListener(()=>{d.tutorialSeen=true;GameApp.I.Save();Destroy(panel);dialogOpen=false;});}
 void Refresh(){stats.text=$"YEAR {d.year}  LEVEL {d.level}  XP {d.xp}\nMONEY {d.money:N0}  POP {d.population}  FOOD {d.food}  ENERGY {d.energy}  HAPPINESS {d.happiness}%";mission.text=Missions.Get(d);for(int i=0;i<12;i++){var t=grid.GetChild(i).GetComponentInChildren<TextMeshProUGUI>();int lv=d.buildings[i].level;t.text=names[i]+"\n"+(lv==0?"BUILD • "+cost[i]:"LEVEL "+lv+" • UPGRADE "+(lv<3?cost[i]*(lv+1):"MAX"));}}
 void Update(){if(Input.GetKeyDown(KeyCode.Escape)&&!dialogOpen)Pause();}
}