using UnityEngine;using UnityEngine.UI;using TMPro;
public class BharatRiseGame:MonoBehaviour{
 class D{public int money=2500,pop=120,food=120,energy=100,happy=55,year=1,level=1;public bool[] built=new bool[6];}
 D d;TextMeshProUGUI stats,msg;Transform grid;string[] n={"Homes","Farm","School","Solar","Hospital","Market"};int[] c={500,350,700,900,850,650};
 void Awake(){Application.targetFrameRate=60;Load();UI();Refresh();}
 void Load(){string x=PlayerPrefs.GetString("BR_SAVE","");d=string.IsNullOrEmpty(x)?new D():JsonUtility.FromJson<D>(x);if(d.built==null)d.built=new bool[6];}
 void Save(){PlayerPrefs.SetString("BR_SAVE",JsonUtility.ToJson(d));PlayerPrefs.Save();}
 TextMeshProUGUI T(string s,Transform p,int z){var g=new GameObject("Text");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;var t=g.AddComponent<TextMeshProUGUI>();t.text=s;t.fontSize=z;t.alignment=TextAlignmentOptions.Center;t.color=Color.white;t.enableAutoSizing=true;t.fontSizeMin=14;t.fontSizeMax=z;return t;}
 Button B(string s,Transform p){var g=new GameObject("Button");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.sizeDelta=new Vector2(300,210);g.AddComponent<Image>().color=new Color(.10f,.24f,.32f,1);var b=g.AddComponent<Button>();T(s,g.transform,34);return b;}
 void UI(){var co=new GameObject("Canvas").AddComponent<Canvas>();co.renderMode=RenderMode.ScreenSpaceOverlay;var sc=co.gameObject.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1080,1920);co.gameObject.AddComponent<GraphicRaycaster>();var bg=new GameObject("Background");bg.transform.SetParent(co.transform,false);var br=bg.AddComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;bg.AddComponent<Image>().color=new Color(.035f,.07f,.11f,1);
 var title=T("BHARAT RISE",bg.transform,58);title.rectTransform.anchorMin=new Vector2(.05f,.92f);title.rectTransform.anchorMax=new Vector2(.95f,.99f);
 stats=T("",bg.transform,30);stats.rectTransform.anchorMin=new Vector2(.04f,.80f);stats.rectTransform.anchorMax=new Vector2(.96f,.91f);
 var gg=new GameObject("DistrictGrid");gg.transform.SetParent(bg.transform,false);grid=gg.transform;var gl=gg.AddComponent<GridLayoutGroup>();gl.cellSize=new Vector2(300,210);gl.spacing=new Vector2(24,24);gl.constraint=GridLayoutGroup.Constraint.FixedColumnCount;gl.constraintCount=2;var gr=gg.GetComponent<RectTransform>();gr.anchorMin=new Vector2(.08f,.30f);gr.anchorMax=new Vector2(.92f,.79f);gr.offsetMin=gr.offsetMax=Vector2.zero;
 for(int i=0;i<6;i++){int k=i;var b=B(n[i]+"\n₹"+c[i],grid);b.onClick.AddListener(()=>Build(k));}
 var next=B("NEXT YEAR  ▶",bg.transform);next.GetComponent<RectTransform>().anchorMin=new Vector2(.12f,.17f);next.GetComponent<RectTransform>().anchorMax=new Vector2(.88f,.24f);next.GetComponent<RectTransform>().sizeDelta=Vector2.zero;next.onClick.AddListener(Next);
 var reset=B("RESET",bg.transform);reset.GetComponent<RectTransform>().anchorMin=new Vector2(.35f,.07f);reset.GetComponent<RectTransform>().anchorMax=new Vector2(.65f,.12f);reset.GetComponent<RectTransform>().sizeDelta=Vector2.zero;reset.onClick.AddListener(()=>{PlayerPrefs.DeleteKey("BR_SAVE");Load();msg.text="New city started.";Refresh();});
 msg=T("Build districts and grow your city.",bg.transform,28);msg.rectTransform.anchorMin=new Vector2(.06f,.245f);msg.rectTransform.anchorMax=new Vector2(.94f,.29f);}
 void Build(int i){if(d.built[i]){msg.text=n[i]+" already built.";return;}if(d.money<c[i]){msg.text="Not enough funds.";return;}d.money-=c[i];d.built[i]=true;d.pop+=i==0?40:0;d.food+=i==1?70:i==5?25:0;d.energy+=i==3?90:i==5?20:0;d.happy=Mathf.Clamp(d.happy+new[]{5,8,14,10,18,10}[i],0,100);msg.text=n[i]+" completed!";Save();Refresh();}
 void Next(){d.year++;d.money+=d.pop*4+d.food/10;d.food=Mathf.Max(0,d.food-d.pop/3);d.energy=Mathf.Max(0,d.energy-d.pop/5);d.happy=Mathf.Clamp(d.happy+(d.food>0?2:-8)+(d.energy>0?2:-7),0,100);if(d.happy>70&&d.pop>200)d.level=Mathf.Min(10,d.level+1);if(d.food<=0||d.energy<=0)d.pop=Mathf.Max(40,d.pop-20);msg.text="Year "+d.year+" begins. Keep resources positive.";Save();Refresh();}
 void Refresh(){stats.text=$"YEAR {d.year}  •  LEVEL {d.level}\n₹{d.money:N0}   👥 {d.pop}   🌾 {d.food}   ⚡ {d.energy}   ❤ {d.happy}%";for(int i=0;i<grid.childCount;i++){var t=grid.GetChild(i).GetComponentInChildren<TextMeshProUGUI>();t.text=d.built[i]?n[i]+"\n✓ BUILT":n[i]+"\n₹"+c[i];}}
}