using UnityEngine;using UnityEngine.SceneManagement;using UnityEngine.UI;using TMPro;
public class SceneEntry:MonoBehaviour{
 public string sceneName; Canvas canvas;
 void Start(){if(FindObjectOfType<GameApp>()==null)new GameObject("GameApp").AddComponent<GameApp>();Build();}
 TextMeshProUGUI T(string s,Transform p,int size){var g=new GameObject("Text");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.anchorMin=Vector2.zero;r.anchorMax=Vector2.one;r.offsetMin=r.offsetMax=Vector2.zero;var t=g.AddComponent<TextMeshProUGUI>();t.text=s;t.fontSize=size;t.alignment=TextAlignmentOptions.Center;t.color=Color.white;t.enableAutoSizing=true;t.fontSizeMin=14;t.fontSizeMax=size;return t;}
 Button B(string label,Transform p){var g=new GameObject("Button");g.transform.SetParent(p,false);var r=g.AddComponent<RectTransform>();r.sizeDelta=new Vector2(720,130);g.AddComponent<Image>().color=new Color(.10f,.32f,.46f,1);var b=g.AddComponent<Button>();T(label,g.transform,34);return b;}
 void Build(){canvas=new GameObject("Canvas").AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var sc=canvas.gameObject.AddComponent<CanvasScaler>();sc.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;sc.referenceResolution=new Vector2(1080,1920);canvas.gameObject.AddComponent<GraphicRaycaster>();var bg=new GameObject("Background");bg.transform.SetParent(canvas.transform,false);var br=bg.AddComponent<RectTransform>();br.anchorMin=Vector2.zero;br.anchorMax=Vector2.one;br.offsetMin=br.offsetMax=Vector2.zero;bg.AddComponent<Image>().color=new Color(.025f,.055f,.09f,1);
 var title=T("BHARAT RISE",bg.transform,72);title.rectTransform.anchorMin=new Vector2(.08f,.72f);title.rectTransform.anchorMax=new Vector2(.92f,.86f);
 var sub=T(sceneName=="MainMenu"?"BUILD • GROW • LEAD":"BHARAT RISE",bg.transform,28);sub.rectTransform.anchorMin=new Vector2(.1f,.64f);sub.rectTransform.anchorMax=new Vector2(.9f,.71f);
 if(sceneName=="MainMenu"){var b=B("▶  PLAY",bg.transform);Pos(b,.15f,.47f,.85f,.56f);b.onClick.AddListener(()=>SceneManager.LoadScene("City"));var c=B("⚙  SETTINGS",bg.transform);Pos(c,.15f,.34f,.85f,.43f);c.onClick.AddListener(()=>SceneManager.LoadScene("Settings"));var h=B("★  ACHIEVEMENTS",bg.transform);Pos(h,.15f,.21f,.85f,.30f);h.onClick.AddListener(()=>SceneManager.LoadScene("Achievements"));var q=B("EXIT / RESET",bg.transform);Pos(q,.15f,.08f,.85f,.17f);q.onClick.AddListener(()=>{GameApp.I.NewGame();});}
 else if(sceneName=="Settings"){var b=B("←  BACK",bg.transform);Pos(b,.12f,.12f,.88f,.21f);b.onClick.AddListener(()=>SceneManager.LoadScene("MainMenu"));var x=B("RESET CITY SAVE",bg.transform);Pos(x,.12f,.48f,.88f,.57f);x.onClick.AddListener(()=>{GameApp.I.NewGame();SceneManager.LoadScene("City");});}
 else if(sceneName=="Achievements"){var d=GameApp.I.Data;var info=T("Milestones\n\nLEVEL 10: "+(d.level>=10?"✓":"—")+"\n200+ POPULATION: "+(d.population>=200?"✓":"—")+"\n5000+ MONEY: "+(d.money>=5000?"✓":"—")+"\nHAPPINESS 80+: "+(d.happiness>=80?"✓":"—")+"\nALL DISTRICTS: "+(AllBuilt(d)?"✓":"—"),bg.transform,32);info.rectTransform.anchorMin=new Vector2(.1f,.30f);info.rectTransform.anchorMax=new Vector2(.9f,.70f);var b=B("←  BACK",bg.transform);Pos(b,.12f,.12f,.88f,.21f);b.onClick.AddListener(()=>SceneManager.LoadScene("MainMenu"));}
 }
 bool AllBuilt(GameData d){for(int i=0;i<d.buildings.Length;i++)if(!d.buildings[i])return false;return true;}
 void Pos(Button b,float a,float c,float x,float y){var r=b.GetComponent<RectTransform>();r.anchorMin=new Vector2(a,c);r.anchorMax=new Vector2(x,y);r.offsetMin=r.offsetMax=Vector2.zero;}
}